### ISSUE TITLE
Little note about one extension in your package that slow vscode intellisense

### ISSUE THREAD

**Issue by nasreddineskandrani** [johnpapa/vscode-angular-essentials#19]
Hi,
Please find in this issue https://github.com/angular/vscode-ng-language-service/issues/44 a status about one extension you are including in your package that slow vscode intellisense.

Can you please try the steps i described in the linked issue and tell me if you are able to see the problem your side. 

Thank you in advanced.

*i tried to setup all settings from the readme of your package the problem was still there until i disabled this extension

**Comment by thibaud-sanchez** [comment]
Same problem, each ctrl+space take more than 10sec.
Disabling this extension resolve the problem : https://marketplace.visualstudio.com/items?itemName=Angular.ng-template

vscode: 1.29.1
vscode-ng-language-service: 0.1.10

**Comment by JohnnyDevNull** [comment]
I'am wondering that this issue still exists. I have this problem since a few weeks and i'am very disappointed about it. I'am working on a Windows 10 with the latest VSCode and Angular and not that much extensions, but without the Angular language service i cannot work on my 10+ Apps projects at work.

vscode: 1.32.1 (system setup)
vscode-ng-language-service: 0.1.11

[EDIT]:

Well i think i found the problem in my case...

I have a library setup in my workspace where the build /dist/mylib/ is referenced in the (tsconfig.json).paths section. With this setup the angular language service load time increased to a minimum of 30 and more seconds for the **getTemplateReferences** loadtime. After that it runs faster, but then i run in permission errors when i rebuild the library because the files are in use and the angular language service have to reload the references on a rebuild, so the loadtime goes every time down.

Update:

I think it's the combination of the library setup and the barell imports we are using for the lib:
https://basarat.gitbooks.io/typescript/docs/tips/barrel.html

On a another dev computer the loading time takes every time 16 seconds also when the file is closed and reopened or a reference on a attribute within a class itself. The IntelliSense is not getting cached there.

**Comment by johnpapa** [comment]
closing in favor of the fixes coming to ALS

**Comment by JWess** [comment]
@johnpapa Can you point us to those fixes or something that talks about those fixes...or explain them yourself?
